### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Kureev** [raphamorim/native-css#1]
I think a lot of people would be interested in supporting this project. Please, add roadmap section to your readme.

**Comment by raphamorim** [comment]
Before adding the roadmap. Better define some points.

Points to the Roadmap, which I think is valid:
- Integration with gulp
- Fix conversion problem for classes as `.father.isActive`
- Enable conversion for media querie (thinking outside the react-native, what do you think?)
- And add more tests (necessary)

Would you like to suggest something?
