### ISSUE TITLE
convert issue

### ISSUE THREAD

**Issue by laboratoryyingong** [raphamorim/native-css#20]
Hi,

When I use native-css, I found a weird issue that sometimes it will export error format in-line styles, for instance, "background-color": "#F8F8F8" => "background-color": "#F8F8F8"(should be "backgroundColor": "#F8F8F8")

Thanks & Regards!

**Comment by raphamorim** [comment]
hmm, makes a lot of sense =)
I'll put this issue on "help wanted", feel free if you want to help it.

**Comment by raphamorim** [comment]
Hi, @laboratoryyingong I maded this fixes and publish on `native-css@2.0.0` :octocat: 
Thanks for reporting :)
