### ISSUE TITLE
Accept other input Formats (URL, Buffer)

### ISSUE THREAD

**Issue by DoubleU23** [raphamorim/native-css#9]
provide support for

URL (Http Request)
and/or
Buffer

to ensure easier extended usage in other environments (f.e. webpack)

**Comment by raphamorim** [comment]
Yeah, support to URL is a good suggestion. 
I'll implement it, before see the buffer option.

What do you think?

**Comment by DoubleU23** [comment]
i don't see any buffer option?
don't know what you mean...

accepting Buffers would massively enhance your module to use it in the terminal and with other modules
it's harder to implement...

accepting URLs should be easy,
maybe i'll make a pull request

**Comment by DoubleU23** [comment]
by the way... i'm currently builing a webpack loader using your module...
accepting urls would make it really easy... i still have trouble to write (asyc) to a tmp file and wait until its written (node n00b)

but it's (nearly) working...
it breaks on the first build because it reads before its written...
maybe you want to take a look ;)(doubleU23/cssobjects-loader)

**Comment by raphamorim** [comment]
I can do with buffer as well. Intends to send the PR?

**Comment by DoubleU23** [comment]
i won't find the time the next days and im not deep enough into node to implement the buffer option...
i could make the URL part, maybe on friday

and i would love if you can implement buffers... then i'll share my loader for your module ;)

**Comment by DoubleU23** [comment]
no intends if you can do it yourself... i got enough work for the next days/weeks...

**Comment by DoubleU23** [comment]
i added basic URL support for script-usage...  
see #13

**Comment by raphamorim** [comment]
Tnx for the contributions
Related: #13  #14
